version: '3'
services:
  learn-mysql:
    image: percona:5.6.41
    platform: linux/x86_64
    privileged: true
    volumes:
      - docker-db:/var/lib/mysql
    container_name: learn-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Welcome@1
    ports:
      - '3306:3306'
volumes:
  docker-db:
